parameters:
#    px_security.example.class: Pixellary\SecurityBundle\Example

services:
#    px_security.example:
#        class: %px_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
